### ISSUE TITLE
Bug Bash

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-javascript#106]

**Comment by luisquintanilla** [comment]
Chat Text Box overlaps with conversation

![image](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/46974588/203ec9f4-0478-49f3-9bf8-02359ea5a546)

**Comment by luisquintanilla** [comment]
Clicking on support document returns 404.

![image](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/46974588/73214b89-139e-480c-b62e-01b1b1d135e1)

**Comment by pamelafox** [comment]
The endpoint URI isn't obvious when `azd up` finishes. Maybe the postdeploy step could be earlier? (Postprovision?) Or could it be shorter, like by removing the funding notice in npmrc?

![Screenshot 2023-11-02 at 10 12 48 AM](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/297042/de39d343-f425-4673-96c0-fd86a538531e)

**Comment by pamelafox** [comment]
Funky alignment of headings

![Screenshot 2023-11-02 at 10 24 15 AM](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/297042/d5bf8952-adac-4020-91ba-350709935623)

**Comment by pamelafox** [comment]
Response included "Followup questions: " before the citations:


![Screenshot 2023-11-02 at 10 26 06 AM](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/297042/45ddc1b8-1be8-419c-beb5-105debe75482)

**Comment by pamelafox** [comment]
Follow-up questions have no question marks:

![Uploading Screenshot 2023-11-02 at 10.25.56 AM.png…]()

**Comment by pamelafox** [comment]
"Show thought process" button is greyed out on previous question when I have clicked it on later question.
![Screenshot 2023-11-02 at 10 30 42 AM](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/297042/3cafb884-92c9-45d5-8033-e73718ce8ac9)

**Comment by pamelafox** [comment]
Doc says to check "Suggest follow-up questions" but it seems to already be default on. Not sure if the app wants to keep it on (its off for Python) or if docs should change.

![Screenshot 2023-11-02 at 10 35 39 AM](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/297042/1bf471e1-0f92-48af-9cbc-e8894b1ba665)

**Comment by anfibiacreativa** [comment]
> Clicking on support document returns 404.
> 
> ![image](https://user-images.githubusercontent.com/46974588/280071538-73214b89-139e-480c-b62e-01b1b1d135e1.png)
> 
> ```json
> {
>     "statusCode": 404,
>     "error": "Not Found",
>     "message": "Not Found"
> }
> ```

Will be fixed with #103

**Comment by anfibiacreativa** [comment]
> "Show thought process" button is greyed out on previous question when I have clicked it on later question. ![Screenshot 2023-11-02 at 10 30 42 AM](https://user-images.githubusercontent.com/297042/280078461-3cafb884-92c9-45d5-8033-e73718ce8ac9.png)

This is the expected behavior. The button is disabled when the panel is open.

**Comment by anfibiacreativa** [comment]
> Response included "Followup questions: " before the citations:
> 
> ![Screenshot 2023-11-02 at 10 26 06 AM](https://user-images.githubusercontent.com/297042/280076658-45ddc1b8-1be8-419c-beb5-105debe75482.png)

I think this is an edge case but we will try to reproduce.

**Comment by sinedied** [comment]
> Clicking on support document returns 404.
> 
> ![image](https://user-images.githubusercontent.com/46974588/280071538-73214b89-139e-480c-b62e-01b1b1d135e1.png)
> 
> ```json
> {
>     "statusCode": 404,
>     "error": "Not Found",
>     "message": "Not Found"
> }
> ```

This one is prompt-related, as it generates an extra `source: ` in front of the filename sometimes. 
GPT35 needs careful prompting to follow format instructions correctly 😅

**Comment by anfibiacreativa** [comment]
All items have been solved or are in progress.
