### ISSUE TITLE
BugBash - Docs -*

### ISSUE THREAD

**Issue by luisquintanilla** [Azure-Samples/azure-search-openai-javascript#107]

**Comment by luisquintanilla** [comment]
In the cleanup resources document, the command should be:

```bash
azd down --purge
```

**Comment by luisquintanilla** [comment]
For prerequisites, the Azure Account requires certain permissions.

> Azure account permissions - Your Azure Account must have Microsoft.Authorization/roleAssignments/write permissions, such as [User Access Administrator](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#user-access-administrator) or [Owner](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#owner).

**Comment by anfibiacreativa** [comment]
> For prerequisites, the Azure Account requires certain permissions.
> 
> > Azure account permissions - Your Azure Account must have Microsoft.Authorization/roleAssignments/write permissions, such as [User Access Administrator](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#user-access-administrator) or [Owner](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#owner).

I'm not sure I understand the necessary update. Are you suggesting we move this to pre-requisites?

**Comment by glaucia86** [comment]
I think @luisquintanilla meant to update the preview documentation that @dfberry is working on, to include `--purge`, @anfibiacreativa

**Comment by dfberry** [comment]
@glaucia86  can you create a PR to the repo for the README.md change for `azd down --purge`. I already have this change in the 1st party docs release branch.

**Comment by glaucia86** [comment]
> @glaucia86 can you create a PR to the repo for the README.md change for `azd down --purge`. I already have this change in the 1st party docs release branch.

Hi, @dfberry! Sure!

**Comment by glaucia86** [comment]
> For prerequisites, the Azure Account requires certain permissions.
> 
> > Azure account permissions - Your Azure Account must have Microsoft.Authorization/roleAssignments/write permissions, such as [User Access Administrator](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#user-access-administrator) or [Owner](https://learn.microsoft.com/azure/role-based-access-control/built-in-roles#owner).

Hi, @luisquintanilla. This information is already in the README.md file here: 

https://github.com/Azure-Samples/azure-search-openai-javascript/blob/main/README.md?plain=1#L80

**Comment by glaucia86** [comment]
Hi, @dfberry, @anfibiacreativa and @luisquintanilla

Pull Request opened here: **#125**

**Comment by anfibiacreativa** [comment]
All items have been solved.
