### ISSUE TITLE
Run "azd up" fails in Dev Containers

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/azure-search-openai-javascript#119]
**Describe the issue:**
An error occurred when running `azd up` as follows：
![image](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/af22d2c3-c397-4e81-a09b-dc51ba00e8e0)

**Environment:**
- Readme - Dev Container
- Learn Docs - Dev Container

**Repro Steps:**
1. Click button in [README.md](https://github.com/Azure-Samples/azure-search-openai-javascript#vs-code-remote-containers)
2. Run `azd auth login`
3. Run `azd up`

**Expected behavior**
Run `azd up`  no error.

@charris-msft for notification.

**Comment by shibbas** [comment]
I cannot reproduce this issue @NanaXiong00. Can you provide more information about your Docker setup? Please ensure your docker is setup as instructed here under installation: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers

**Comment by anfibiacreativa** [comment]
@NanaXiong00 can you please retest? It was probably fixed with #127

**Comment by NanaXiong00** [comment]
@anfibiacreativa We retested it based on the latest code, and the result was `pass` in Dev Container. We will close this issue.
