### ISSUE TITLE
Unable to successfully load data when running "azd up"

### ISSUE THREAD

**Issue by NanaXiong00** [Azure-Samples/azure-search-openai-javascript#120]
**Describe the issue:**
Run `azd up`, the data could not be loaded successfully. The details are as follows:
<img width="800" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/cb66591a-fbf5-472e-9fb7-a09a1a311375">
<img width="800" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/79b811a3-2391-48ec-a704-20d3c71b1897">
<img width="800" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/58a2db19-3ab2-471d-aa30-37cf7d296019">

**Environment:**
- Readme - Local
- Learn Docs - Local

**Repro Steps:**
1. Run `azd auth login`
2. Run `azd init -t azure-search-openai-javascript` 
3. Run `azd up`

**Expected behavior**
Running `azd up` can add data and the web page will respond correctly, such as the following.
<img width="600" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/0175517e-c471-4867-bedb-79013e277ba9">

![image](https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/580baaa2-b549-4fe6-a1b2-98c0b134327c)

@charris-msft for notification.

**Comment by NanaXiong00** [comment]
@sinedied, Tested with the latest code following **Repro Steps** above, we found an new error when run `azd up` locally. Please help resolve. The details are as follows:
<img width="800" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/138103031/05d90af2-1762-4bce-a3d0-889214b279a5">

**azd version**:
-  azd version 1.4.3 (commit d165bd2de96dae75de57604c0d8a5553ae214618)

**Comment by sinedied** [comment]
Thanks @NanaXiong00 for the update. I've reopened the issue to investigate this

**Comment by sinedied** [comment]
Could test if this change solves the issue for you? https://github.com/Azure-Samples/azure-search-openai-javascript/pull/139
I was able to test it in Codespaces, but I don't have a Windows environment at hand to see if something works differently there.
Thank you

**Comment by NanaXiong00** [comment]
> Could you test if the change in this PR solves the issue for you? #139 I was able to test it in Codespaces, but I don't have a Windows environment at hand to see if something works differently there. Thank you

@sinedied Based on this pr, the local test was successful in the windows environment. 🎉
