### ISSUE TITLE
Upgrade repo to latest azd/infra/core

### ISSUE THREAD

**Issue by jongio** [Azure-Samples/azure-search-openai-javascript#130]
This repo uses an old version of azd/infra/core.  There have been many improvements and security updates since this version. Please upgrade to latest found here: 

https://github.com/Azure/azure-dev/tree/main/templates/common/infra/bicep

Good example of swa: https://github.com/Azure/azure-dev/blob/main/templates/todo/projects/nodejs-mongo-swa-func/.repo/bicep/infra/main.bicep

Good example of aca: https://github.com/Azure/azure-dev/blob/main/templates/todo/projects/nodejs-mongo-aca/.repo/bicep/infra/main.bicep

**Comment by sinedied** [comment]
@jongio I updated all templates and added the required user assigned identity for the container apps in this branch: https://github.com/Azure-Samples/azure-search-openai-javascript/tree/infra-update

But when deploying I get this error:
<img width="1348" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/593151/54037a2e-c106-4c4d-ab85-aa2e9f5b7286">

Did I missed something? Thanks for your help

**Comment by anfibiacreativa** [comment]
@sinedied @jongio Any updates here?

**Comment by jongio** [comment]
Can you make sure you have the latest infra/core (it may have changed since your last sync).

Also, please compare your bicep with the bicep from the other azure-search-openai templates that use aca.
