### ISSUE TITLE
 AzureML Chat Backend Protocol link is pointing to the non-existent repo (404)

### ISSUE THREAD

**Issue by angrynerds-beniamin** [Azure-Samples/azure-search-openai-javascript#150]
The link (https://github.com/Azure/azureml_run_specification/blob/chat-protocol/specs/chat-protocol/chat-app-protocol.md) to the 
AzureML Chat Backend Protocol is pointing to the non-existent repo. 

```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by sinedied** [comment]
Yes sorry for that, the linked repo is currently under review for getting open-sourced, so the current link is not working.

In the meantime, you can get some information about the protocol [here](https://moaw.dev/workshop/?src=gh%3Aazure-samples%2Fazure-openai-rag-workshop%2Fmain%2Fdocs%2F&step=3#the-chat-backend-protocol).
