### ISSUE TITLE
[bug] parsing issues in frontend

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#166]
Sometime the parser fails at parsing some answers, for example for the question "How to contact a representative?" I get this:

<img width="801" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/593151/087eabc7-bb50-47bc-8475-a63f739087f1">

This also occurs quite often when trying to cite sources when the backend is switched to the Python sample:

<img width="1696" alt="image" src="https://github.com/Azure-Samples/azure-search-openai-javascript/assets/593151/400503ac-bdfd-44f7-b5d0-564d63411a66">

### This issue is for a: (mark with an `x`)

```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

**Comment by anfibiacreativa** [comment]
We have reproduced and this typically happens when the LLM returns a phone number.

**Comment by zaccariafra** [comment]
I was also facing this issue, getting a response splitted in bullets. While trying to solve the issue, I found out that disabling the "Stream chat completion responses" option somehow solves the issue.
Didn't investigate more, but the issue might be related to generating the array that contains the response.

I hope it can help somehow

**Comment by anfibiacreativa** [comment]
> I was also facing this issue, getting a response splitted in bullets. While trying to solve the issue, I found out that disabling the "Stream chat completion responses" option somehow solves the issue. Didn't investigate more, but the issue might be related to generating the array that contains the response.
> 
> I hope it can help somehow

Thank you for the context. We're evaluating moving that responsibility to the backend. Earlier when we delivered this sample, that was not possible, but we always planned to migrate the parser for performance reasons.  I will reprioritize.

**Comment by nmahajanoii** [comment]
any update on the issue?
