### ISSUE TITLE
Create modular component to verify quality of response

### ISSUE THREAD

**Issue by dfberry** [Azure-Samples/azure-search-openai-javascript#173]
1) Create a FE UI such as thumbs up/thumbs down to provide feedback on the quality of the response. 
2) Create a BE to capture feedback. 

https://github.com/microsoft/sample-app-aoai-chatGPT/pull/396

@PamelaFox please edit/update with any more requirements.

**Comment by pamelafox** [comment]
Here's the Python issue from developers requesting it:
https://github.com/Azure-Samples/azure-search-openai-demo/issues/489
You might get more ideas there. Also from checking to see how GitHub Copilot and ChatGPT do it.

I wonder whether it should include an admin-auth'd frontend for reviewing the feedback, and/or dashboards showing its rate over time, alerts for low numbers, etc.
