### ISSUE TITLE
Deployment Failed

### ISSUE THREAD

**Issue by mirojs** [Azure-Samples/azure-search-openai-javascript#61]
> ## Please provide us with the following information:

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Codespaces deployment failed (beyond the web app deployment link showing up) with error below:

Besides, the deployment part of the README.md file is not a corresponding one. Please double check it, including the link.
### Minimal steps to reproduce

>

### Any log messages given by the failure

>
Running "index-files" CLI tool
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/workspaces/azure-search-openai-javascript/packages/indexer/dist/lib/cli.js' imported from /workspaces/azure-search-openai-javascript/packages/indexer/bin/index-files.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:327:11)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.18.0

ERROR: failed running post hooks: 'postup' hook failed with exit code: '1', Path: './scripts/index-data.sh'. : exit code: 1

### Expected/desired behavior

> Normal deployment

### OS and Version?

> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?) Linux

### azd version? 

> run `azd version` and copy paste here.

### Versions

>1.3.1

### Mention any other details that might be useful

> ---
>
> Thanks! We'll be in touch soon.

**Comment by andresfelipe66** [comment]
Hello Guys, the accelerator looks awesome. I have the same problem. 
Using Windows 11.
Thanks

**Comment by mirojs** [comment]
@sinedied Great! Thanks for keeping improving this demo.
