### ISSUE TITLE
[feature][typechat] add support for task detection in chat interface

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#8]
We would like to integrate TypeChat in the project. An example idea would be to use it to detect specific tasks in the human message, like for example the "send email" task that would allow to send AI results to a list of emails.

Ideally, the task detection implementation should be extensible so other additional tasks could be implemented in a similar way.

#### Tasks
- [ ] add TypeChat integration to detect the "send email" task and allow to send AI replies to specified emails
- [ ] add backend API to support sending emails

**Comment by anfibiacreativa** [comment]
Contributing upstream to LangChain as dependency.
