### ISSUE TITLE
[chat-component] missing features in new experimental chat component

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#91]
Branch is here: https://github.com/Azure-Samples/azure-search-openai-javascript/tree/experimental-chatv2

#### Currently not implemented
- [ ] reset (new chat) button: can be done in react app outside of the component, setting property `messages` of the component to an empty array should do the trick
- [ ] thought process: can be done in a new web component and injected via a slot. Data can be shared with either a [shared context](https://lit.dev/docs/data/context/#context-objects) or using the [`@slotchange` event](https://lit.dev/docs/components/shadow-dom/#accessing-slotted-children), and setting the `.data` property on the slotted element for example
- [ ] copy response button: same as above, or could be a single component englobing the thought process and copy button

**Comment by anfibiacreativa** [comment]
There is plenty more functionality missing, than this. This is why the previous component code was more extense.
- [ ] disable inputs when chat is in progress
- [ ] respect turns
- [ ] enable buttons when chat is started
- [ ] enable buttons when response is complete
- [ ] reset chat
- [ ] capture date and time to enable history
- [ ] display additional default questions

Also currently, the API fails to fetch
