### ISSUE TITLE
[webapp/chat] disable CORS when running in Codespaces

### ISSUE THREAD

**Issue by sinedied** [Azure-Samples/azure-search-openai-javascript#92]
Search API has now CORS enforced, but it needs additional config to update ALLOWED_ORIGINS when in Codespaces.

We shoudl detect if the server is running inside Codespaces and disable CORS restrictions in that case since it's a dev environment to make it easier for users.

**Comment by shibbas** [comment]
This would be needed for the DevContainer VSCode development as well. 
For codespaces, looks like there is a default `CODESPACES` environment variable that can be used. https://docs.github.com/en/codespaces/developing-in-a-codespace/default-environment-variables-for-your-codespace

**Comment by sinedied** [comment]
Yes that's something we can use!
We need more testing to determine if it's still an issue, as adding a proxy config to the Vite config seemed to have fixed the issue for me.

**Comment by anfibiacreativa** [comment]
No longer valid.
